version: '3.8'  # Use a valid Docker Compose version

services:
  app:
    build:
      context: .  # Build from the current directory
      dockerfile: Dockerfile  # Specify Dockerfile
    image: securevoterid
    env_file:
      - .env  # Ensure this file exists at the root
    ports:
      - "5000:5000"  # Expose necessary ports